services:
  icecast:
    image: radio/icecast
    build: ./icecast
    env_file: ./icecast/.env
#    environment:
#      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
#      - ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD}
#      - ICECAST_ADMIN_USERNAME=${ICECAST_ADMIN_USERNAME}
#      - ICECAST_ADMIN_EMAIL=${ICECAST_ADMIN_EMAIL}
#      - ICECAST_LOCATION=${ICECAST_LOCATION}
#      - ICECAST_HOSTNAME=${ICECAST_HOSTNAME}
#      - ICECAST_MAX_CLIENTS=${ICECAST_MAX_CLIENTS}
#      - ICECAST_MAX_SOURCES=${ICECAST_MAX_SOURCES}
#      - ICECAST_ENVIVO_PASSWORD=${ICECAST_ENVIVO_PASSWORD}
    ports:
      - "8000:8000"
      - "8001:8001"
    stop_grace_period: 1s

  ices:
    image: radio/ices
    build: ./ices
    env_file: ./ices/.env
    volumes:
      - type: bind
        source: /home/docker/persistent
        target: /mnt/music
    stop_grace_period: 1s


  liquidsoap:
    image: radio/liquidsoap
    build: ./liquidsoap
    env_file: ./liquidsoap/.env
    stop_grace_period: 1s
