services:
  icecast:
    image: radio/icecast
    build: ./icecast
    environment:
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
      - ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD}
      - ICECAST_ADMIN_USERNAME=${ICECAST_ADMIN_USERNAME}
      - ICECAST_ADMIN_EMAIL=${ICECAST_ADMIN_EMAIL}
      - ICECAST_LOCATION=${ICECAST_LOCATION}
      - ICECAST_HOSTNAME=${ICECAST_HOSTNAME}
      - ICECAST_MAX_CLIENTS=${ICECAST_MAX_CLIENTS}
      - ICECAST_MAX_SOURCES=${ICECAST_MAX_SOURCES}
      - ICECAST_ENVIVO_PASSWORD=${ICECAST_ENVIVO_PASSWORD}
    expose:
      - "8000"
      - "8001"
#	ports:
#      - "8000:8000"
#      - "8001:8001"
    stop_grace_period: 1s
#    entrypoint: /entrypoint.sh


#  liquidsoap:
#    image: radio/liquidsoap
#    build: ./liquidsoap
#    environment:
#      - LIQUIDSOAP_USER=${LIQUIDSOAP_USER}
#      - LIQUIDSOAP_PASS=${LIQUIDSOAP_PASS}
#      - LIQUIDSOAP_HOST=${LIQUIDSOAP_HOST}
#      - LIQUIDSOAP_MOUNT=${LIQUIDSOAP_MOUNT}
#    stop_grace_period: 1s
#    entrypoint: /entrypoint.sh
