services:
  icecast:
    image: radio/icecast
    env_file: ./icecast/env
    build: ./icecast

  liquidsoap:
    image: radio/liquidsoap
    env_file: ./liquidsoap/env
    build: ./liquidsoap
      depends_on: radio/icecast

